[xdebug]
xdebug.mode = off
xdebug.client_host = host.docker.internal
xdebug.start_with_request = no
 
; Or use the host machine IP address:
; xdebug.client_host = 192.168.86.203
 
xdebug.start_with_request = yes
upload_tmp_dir = /tmp
upload_max_filesize = 50M
post_max_size = 128M
; max_execution_time = 300

